### PR TITLE
Fix error for undefined or null params 

### PR DESCRIPTION
**Pull request by sviande**

### CODE REVIEW

**Comment by lh0x00** [comment]
hi, @sviande I forgot about it for so long, can you give me an example of 2 cases: correct use (with the last param) and no last param?

**Comment by sviande** [comment]
Hi, the argsParser func check if the lastParams contains callback for the subscription.
If the lastParam/arguments of the subscription is `null` or `undefined` we can't check on it the properties `{onStop, onReady, onError}`.

In this example the code will throw an error:  #2 
```
const todosFilter= null | undefined;
Meteor.subscribe('todos', todosFilter);
```

**Comment by lh0x00** [comment]
ok and thanks @sviande

**Comment by lh0x00** [comment]
thanks @sviande , I merged and published the new version.
https://atmospherejs.com/lamhieu/hypersubs

**Pull request merged**
